apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsnodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awsnodejs
  template:
    metadata:
      labels:
        app: awsnodejs
    spec:
      containers:
        - name: nodejs
          image: dorisfebrianda93/awsnodejs:TAG
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: awsnodejsaws
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: awsnodejsaws