apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsnodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awsnodejs
  template:
    metadata:
      labels:
        app: awsnodejs
    spec:
      containers:
        - name: nodejs
          image: dorisfebrianda93/awsnodejs:TAG
          ports:
            - containerPort: 6000
          env:
            - name: PORT
              value: "6000"
---
apiVersion: v1
kind: Service
metadata:
  name: awsnodejsaws
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 6000
  selector:
    app: awsnodejsaws