apiVersion: v1
kind: Pod
metadata:
  name: helloworld.oracleau.cloud
  labels:
    app: helloworld.oracleau.cloud
spec:
  containers:
  - name: awsnodejs
    image: awsnodejs:TAG
    ports:
    - name: nodejs-port
      containerPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: awsnodejsservice
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 6000
  selector:
    app: awsnodejsservice